"use strict";
exports.__esModule = true;
var library_1 = require("./files.ts/library");
var bookClass_1 = require("./files.ts/bookClass");
var magazineClass_1 = require("./files.ts/magazineClass");
var clientClass_1 = require("./files.ts/clientClass");
var authors = ['Pedro', 'Rosa', 'Juan', 'Araceli'];
var genres = ['Drama', 'Terror', 'Comedia', 'Vaqueros'];
var book1 = new bookClass_1.Book('Campanita', 50, 'Pedro', 200, 'Este libro habla sobre la historia de un hada..', 'Fantasia');
var book2 = new bookClass_1.Book('Iron man', 150, 'Juan', 300, 'Este libro trata de un multimillonario que se hace superheroe..', 'Ciencia Ficcion');
var magazine1 = new magazineClass_1.Magazine('Para ti', 20, 'Rosa', 20, 5, 2022);
var magazine2 = new magazineClass_1.Magazine('Oeste', 15, 'Araceli', 12, 4, 2021);
var shoppingCart1 = [book1, magazine2];
var shoppingCart2 = [];
var client1 = new clientClass_1.Client('Juan', 'Perez', 38754826, 'Velez Sarfield', authors, genres, 0.3, shoppingCart1);
var client2 = new clientClass_1.Client('Hernan', 'Rodriguez', 58746216, 'Nuñez', authors, genres, 0, shoppingCart2);
var clientlist = [client1, client2];
var bookList = [book1, book2];
var magazineList = [magazine1, magazine2];
var newLibrary = new library_1.Library(clientlist, bookList, magazineList);
newLibrary.soldArticle(client1, magazine1);
console.log(client1);
var compra = newLibrary.viewPurchase(client1, book2);
console.log(compra);
