"use strict";
exports.__esModule = true;
var claseCliente_1 = require("./claseCliente");
var claseRevista_1 = require("./claseRevista");
var claseLibro_1 = require("./claseLibro");
var claseLibreria_1 = require("./claseLibreria");
var autores = ['Pedro', 'Rosa', 'Juan', 'Araceli'];
var generos = ['Drama', 'Terror', 'Comedia', 'Vaqueros'];
var cliente1 = new claseCliente_1.Cliente('Juan', 'Perez', 11111, 'Velez Sarfield', autores, generos, 0.1);
var cliente2 = new claseCliente_1.Cliente('Hernan', 'Rodriguez', 112212, 'Nuñez', autores, generos, 0.3);
var libro1 = new claseLibro_1.Libro('Campanita', 50, 'Pedro', 200, 'Comedia', 'sadfasdasdasdasdsad');
var libro2 = new claseLibro_1.Libro('iron man', 150, 'Juan', 300, 'Drama', 'asfasdadqdq');
var revista1 = new claseRevista_1.Revista('Para ti', 20, 'Rosa', 20, 5, 2022);
var revista2 = new claseRevista_1.Revista('Oeste', 15, 'Araceli', 12, 4, 2021);
var arregloCliente = [cliente1, cliente2];
var arregloLibro = [libro1, libro2];
var arregloRevista = [revista1, revista2];
var libreria1 = new claseLibreria_1.Libreria(arregloCliente, arregloLibro, arregloRevista);
var primerPrecio = libreria1.calcularPrecio(cliente1, libro1);
console.log(primerPrecio);
